INSERT INTO GENRE (NAME) SELECT 'Комедия' WHERE NOT EXISTS (SELECT * FROM GENRE WHERE NAME='Комедия');
INSERT INTO GENRE (NAME) SELECT 'Драма' WHERE NOT EXISTS (SELECT * FROM GENRE WHERE NAME='Драма');
INSERT INTO GENRE (NAME) SELECT 'Мультфильм' WHERE NOT EXISTS (SELECT * FROM GENRE WHERE NAME='Мультфильм');
INSERT INTO GENRE (NAME) SELECT 'Триллер' WHERE NOT EXISTS (SELECT * FROM GENRE WHERE NAME='Триллер');
INSERT INTO GENRE (NAME) SELECT 'Документальный' WHERE NOT EXISTS (SELECT * FROM GENRE WHERE NAME='Документальный');
INSERT INTO GENRE (NAME) SELECT 'Боевик' WHERE NOT EXISTS (SELECT * FROM GENRE WHERE NAME='Боевик');

INSERT INTO MPA (NAME) SELECT 'G' WHERE NOT EXISTS (SELECT * FROM MPA WHERE NAME='G');
INSERT INTO MPA (NAME) SELECT 'PG' WHERE NOT EXISTS (SELECT * FROM MPA WHERE NAME='PG');
INSERT INTO MPA (NAME) SELECT 'PG-13' WHERE NOT EXISTS (SELECT * FROM MPA WHERE NAME='PG-13');
INSERT INTO MPA (NAME) SELECT 'R' WHERE NOT EXISTS (SELECT * FROM MPA WHERE NAME='R');
INSERT INTO MPA (NAME) SELECT 'NC-17' WHERE NOT EXISTS (SELECT * FROM MPA WHERE NAME='NC-17');


INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES('mail@yandex.ru', 'doloreUpdate', 'est adipisicing', '1976-09-20');
INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES('bel@yandex.com', 'ignoredate', 'dipisicing', '1988-10-21');
INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES('bel@yandex.com3', 'ignoredate3', 'dipisicing3', '1988-10-21');
INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES('bel@yandex.com4', 'ignoredate4', 'dipisicing4', '1988-10-21');
INSERT INTO FILM (NAME, DESCRIPTION, DURATION, RELEASE_DATE, ID_MPA) VALUES('film', 'description about', 150, '1999-10-21', 1);
INSERT INTO FILM (NAME, DESCRIPTION, DURATION, RELEASE_DATE, ID_MPA) VALUES('film2', 'description about2', 150, '2000-10-21', 2);
INSERT INTO FILM (NAME, DESCRIPTION, DURATION, RELEASE_DATE, ID_MPA) VALUES('film3', 'description about3', 150, '2000-10-21', 3);
INSERT INTO LIKES (ID_FILM, ID_USER) VALUES(1, 1);
INSERT INTO LIKES (ID_FILM, ID_USER) VALUES(1, 2);
INSERT INTO FRIENDSHIP (ID_USER, ID_FRIEND) VALUES(1, 2);
INSERT INTO FRIENDSHIP (ID_USER, ID_FRIEND) VALUES(1, 3);
INSERT INTO FILM_GENRE (ID_FILM, ID_GENRE) VALUES(1, 3);
INSERT INTO FILM_GENRE (ID_FILM, ID_GENRE) VALUES(1, 4);